const Rules = {
    MAX_DAY_HUNGRY : 3,
    VICTIM_HUNGRY_PENALTY : 2,
    MINIMUM_GODS_SATISFACTION : 10,
    GODS_SATISFACTION_DAILY_DROP : 10,
    MINIMUM_SACRIFICES_FOR_WEEK : 2,
    MAXIMUM_SACRIFICES_FOR_WEEK : 5,
}