const Rules = {
    MAX_DAYS_HUNGRY : 3,
    VICTIM_HUNGRY_PENALTY : 2,
    MIN_AGE : 18,
    MAX_AGE : 70,
    DAILY_COST_MIN : 8,
    DAILY_COST_MAX : 25,
    WORTH_FOR_GODS_DENOMINATOR : 2,

    MINIMUM_SACRIFICES_FOR_WEEK : 2,
    MAXIMUM_SACRIFICES_FOR_WEEK : 5,

    STARTING_MONEY : 100, 
    STARTING_GODS_SATISFACTION : 50,

    SACRIFICES_QUOTA_NOT_MET_PENALTY : 20,
    SACRIFICES_QUOTA_MET_PRIZE : 30,

    MINIMAL_SKILL_VALUE : 10,
    MAXIMAL_SKILL_VALUE : 90,

    GODS_SATISFACTION_LOWEST : 1,
    GODS_SATISFACTION_MAX : 99,
    MINIMUM_GODS_SATISFACTION : 10,
    GODS_SATISFACTION_DAILY_DROP : 10,

    
}