const Rules = {
    MAX_DAYS_HUNGRY : 3,
    VICTIM_HUNGRY_PENALTY : 2,
    MIN_AGE : 18,
    MAX_AGE : 70,
    DAILY_COST_MIN : 8,
    DAILY_COST_MAX : 25,
    WORTH_FOR_GODS_DENOMINATOR : 2,
    HENCHMEN_SUCCESS_MAX_VALUE: 100,
    HENCHMEN_SUCCESS_MIN_VALUE: 1,

    MINIMUM_SACRIFICES_FOR_WEEK : 2,
    MAXIMUM_SACRIFICES_FOR_WEEK : 5,

    STARTING_MONEY : 100, 
    STARTING_GODS_SATISFACTION : 50,
    STARTING_PRISONERS_COUNT : 5,
    STARTING_HENCHMEN_COUNT : 3,
    STARTING_PRIESTS_COUNT : 2,

    STARTING_DAY : 1,
    STARTING_WEEK : 1,

    SACRIFICES_QUOTA_NOT_MET_PENALTY : 5,
    SACRIFICES_QUOTA_MET_PRIZE : 30,

    MINIMAL_SKILL_VALUE : 10,
    MAXIMAL_SKILL_VALUE : 90,

    GODS_SATISFACTION_LOWEST : 1,
    GODS_SATISFACTION_MAX : 99,
    MINIMUM_GODS_SATISFACTION : 10,
    GODS_SATISFACTION_DAILY_DROP : 10,

    MAX_MONEY_FOR_EVERY_EVIL_WORD_IN_SPEECH : 10,
    EVIL_WORDS : ["evil", "satan", "domination", "curse", "kill", "demon", "cult", "bad", "villain", "empire", "hell", "follower", "mindless", "stupid", "devilish", "demonic",
                    "satanic", "killing", "slaughter", "hellish", ],
    SPOOKY_EVENTS_OCCURENCE_TRESHOLD : 40,
    SPAWN_RANDOM_NPC : 50
}